import { AgentsMcpError } from './errors';

const MAX_CATALOG_AGENTS = 1000;
const MAX_AGENT_ID_LENGTH = 200;
const MAX_AGENT_TITLE_LENGTH = 500;
const MAX_AGENT_DESCRIPTION_LENGTH = 4000;
const MAX_AGENT_TYPE_LENGTH = 100;
const MAX_SCHEMA_FIELDS = 200;
const MAX_SCHEMA_FIELD_NAME_LENGTH = 200;
const MAX_ALLOWED_FILE_TYPES = 100;
const MAX_ALLOWED_FILE_TYPE_LENGTH = 200;
const AGENTS_INVOKE_CONTROL_FIELDS = new Set(['apiKey', 'userId', 'flowId', 'oauthToken', 'baseUrlOverride']);
const AGENTS_MCP_CLIENT_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

export const AGENTS_MCP_CLIENT_ID_HEADER = 'x-ki-buddy-agents-client-id';
export const AGENTS_MCP_AGENT_ID_HEADER = 'x-ki-buddy-agents-agent-id';
export const AGENTS_MCP_FIELD_NAME_HEADER = 'x-ki-buddy-agents-field-name';
export const AGENTS_MCP_FILE_NAME_HEADER = 'x-ki-buddy-agents-file-name';
export const AGENTS_MCP_FILE_SIZE_HEADER = 'x-ki-buddy-agents-file-size';

export type AgentsCatalogSummary = Readonly<{
  agentId: string;
  agentType: string;
  description: string;
  title: string;
}>;

export type AgentsCatalogInventory = Readonly<{
  agents: readonly AgentsCatalogSummary[];
  total: number;
}>;

export type AgentsSchemaField = Readonly<{
  allowed_file_types?: readonly string[];
  description: string;
  name: string;
  required: boolean;
  type: string;
}>;

export type AgentsCatalogDescription = AgentsCatalogSummary &
  Readonly<{
    inputSchema: readonly AgentsSchemaField[];
    outputSchema: readonly AgentsSchemaField[];
  }>;

export type AgentsCatalogSelection = Readonly<{
  description: AgentsCatalogDescription;
  inventory: AgentsCatalogInventory;
}>;

export type AgentsScalarInput = boolean | number | string;
export type AgentsScalarInputs = Readonly<Record<string, AgentsScalarInput>>;
export type AgentsInvokeInputs = AgentsScalarInputs;
export type AgentsInvokeRequest = Readonly<{
  agentId: string;
  agentType: string;
  conversationId: string;
  inputs: AgentsInvokeInputs;
}>;

export type AgentsInvokeCorrelation = Readonly<{
  agentId: string;
}>;

export type AgentsJsonValue = null | boolean | number | string | AgentsJsonValue[] | { [key: string]: AgentsJsonValue };
export type AgentsInvokeResult = AgentsJsonValue;

/** Validates the UUID identity generated by one Agents MCP Adapter process. */
export function isAgentsMcpClientId(value: unknown): value is string {
  return typeof value === 'string' && AGENTS_MCP_CLIENT_ID_PATTERN.test(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function requireString(value: unknown, label: string, maxLength: number, allowEmpty = false): string {
  if (typeof value !== 'string') throw new AgentsMcpError('contract', `${label} must be a string`);
  const normalized = value.trim();
  if (!allowEmpty && normalized.length === 0) {
    throw new AgentsMcpError('contract', `${label} must be a non-empty string`);
  }
  if (normalized.length > maxLength) {
    throw new AgentsMcpError('contract', `${label} exceeds the supported length`);
  }
  return normalized;
}

function normalizeAllowedFileTypes(value: unknown, label: string): readonly string[] | undefined {
  if (value === undefined) return undefined;
  if (!Array.isArray(value) || value.length > MAX_ALLOWED_FILE_TYPES) {
    throw new AgentsMcpError('contract', `${label} must be a supported string array`);
  }
  const seen = new Set<string>();
  return value.map((item) => {
    const fileType = requireString(item, label, MAX_ALLOWED_FILE_TYPE_LENGTH);
    if (seen.has(fileType)) throw new AgentsMcpError('contract', `${label} contains a duplicate value`);
    seen.add(fileType);
    return fileType;
  });
}

function normalizeSchema(value: unknown, label: string): readonly AgentsSchemaField[] {
  if (!Array.isArray(value) || value.length > MAX_SCHEMA_FIELDS) {
    throw new AgentsMcpError('contract', `${label} must be a supported array`);
  }
  const seenNames = new Set<string>();
  return value.map((item): AgentsSchemaField => {
    if (!isRecord(item)) throw new AgentsMcpError('contract', `${label} field must be an object`);
    const name = requireString(item.name, `${label} field name`, MAX_SCHEMA_FIELD_NAME_LENGTH);
    if (seenNames.has(name)) throw new AgentsMcpError('contract', `${label} contains a duplicate field name`);
    seenNames.add(name);
    if (typeof item.required !== 'boolean') {
      throw new AgentsMcpError('contract', `${label} field required must be a boolean`);
    }
    const allowedFileTypes = normalizeAllowedFileTypes(item.allowed_file_types, `${label} allowed_file_types`);
    return {
      name,
      description:
        item.description === undefined || item.description === null
          ? ''
          : requireString(item.description, `${label} field description`, MAX_AGENT_DESCRIPTION_LENGTH, true),
      type: requireString(item.type, `${label} field type`, MAX_AGENT_TYPE_LENGTH),
      required: item.required,
      ...(allowedFileTypes ? { allowed_file_types: allowedFileTypes } : {}),
    };
  });
}

function getCatalogEntries(value: unknown): readonly unknown[] {
  if (!isRecord(value) || value.status !== 'ok') {
    throw new AgentsMcpError('contract', 'Agents catalog response has an invalid envelope');
  }
  if (!Array.isArray(value.agents)) {
    throw new AgentsMcpError('contract', 'Agents catalog agents must be an array');
  }
  if (value.agents.length > MAX_CATALOG_AGENTS) {
    throw new AgentsMcpError('contract', 'Agents catalog exceeds the supported inventory capacity');
  }
  return value.agents;
}

function normalizeCatalogSummary(item: unknown): AgentsCatalogSummary | null {
  if (!isRecord(item)) return null;
  try {
    return {
      agentId: requireString(item.agentId, 'Agents catalog agentId', MAX_AGENT_ID_LENGTH),
      title: requireString(item.agentTitle, 'Agents catalog agentTitle', MAX_AGENT_TITLE_LENGTH),
      description:
        item.agentDescription === undefined || item.agentDescription === null
          ? ''
          : requireString(item.agentDescription, 'Agents catalog agentDescription', MAX_AGENT_DESCRIPTION_LENGTH, true),
      agentType: requireString(item.agentType, 'Agents catalog agentType', MAX_AGENT_TYPE_LENGTH),
    };
  } catch {
    return null;
  }
}

/** Projects all usable entries from an Agents catalog without letting an unrelated bad entry poison discovery. */
export function normalizeAgentsCatalog(value: unknown): AgentsCatalogInventory {
  const seenAgentIds = new Set<string>();
  const agents: AgentsCatalogSummary[] = [];
  for (const item of getCatalogEntries(value)) {
    const summary = normalizeCatalogSummary(item);
    if (!summary || seenAgentIds.has(summary.agentId)) continue;
    seenAgentIds.add(summary.agentId);
    agents.push(summary);
  }

  return { total: agents.length, agents };
}

/** Projects the safe inventory and exact supported schema for one candidate in a single validation pass. */
export function normalizeAgentsCatalogSelection(value: unknown, requestedAgentId: string): AgentsCatalogSelection {
  const inventory = normalizeAgentsCatalog(value);
  const description = inventory.agents.find(({ agentId }) => agentId === requestedAgentId);
  if (!description) throw new AgentsMcpError('not_found', 'Agent is not in the current catalog');
  const catalogRecord = getCatalogEntries(value).find(
    (item) => normalizeCatalogSummary(item)?.agentId === requestedAgentId
  );
  if (!isRecord(catalogRecord)) throw new AgentsMcpError('not_found', 'Agent is not in the current catalog');
  return {
    inventory,
    description: {
      ...description,
      inputSchema: normalizeSchema(catalogRecord.defaultInputModes ?? [], 'Agents input schema'),
      outputSchema: normalizeSchema(catalogRecord.defaultOutputModes ?? [], 'Agents output schema'),
    },
  };
}

function validateScalarValue(field: AgentsSchemaField, value: unknown): value is AgentsScalarInput {
  switch (field.type.toLowerCase()) {
    case 'text':
    case 'string':
    case 'date':
    case 'datetime':
      return typeof value === 'string';
    case 'number':
      return typeof value === 'number' && Number.isFinite(value);
    case 'integer':
      return typeof value === 'number' && Number.isSafeInteger(value);
    case 'boolean':
      return typeof value === 'boolean';
    default:
      return false;
  }
}

function validateInputObject(description: AgentsCatalogDescription, value: unknown): AgentsInvokeInputs {
  if (!isRecord(value)) throw new AgentsMcpError('invalid_input', 'Agents invoke inputs must be an object');
  const schemaByName = new Map(description.inputSchema.map((field) => [field.name, field]));
  const entries = Object.entries(value);
  if (entries.length > description.inputSchema.length) {
    throw new AgentsMcpError('invalid_input', 'Agents invoke inputs contain fields outside the exact schema');
  }

  const normalizedEntries: Array<[string, AgentsScalarInput]> = [];
  for (const [name, input] of entries) {
    const field = schemaByName.get(name);
    if (!field || AGENTS_INVOKE_CONTROL_FIELDS.has(name)) {
      throw new AgentsMcpError('invalid_input', 'Agents invoke inputs contain a forbidden field');
    }
    if (field.type.toLowerCase() === 'file') {
      if (typeof input !== 'string' || input.trim().length === 0) {
        throw new AgentsMcpError('invalid_input', 'Agents file input must be a non-empty uploaded file URL');
      }
      normalizedEntries.push([name, input]);
      continue;
    }
    if (!validateScalarValue(field, input)) {
      throw new AgentsMcpError('invalid_input', 'Agents invoke input does not match the exact scalar schema');
    }
    normalizedEntries.push([name, input]);
  }

  const normalized = Object.fromEntries(normalizedEntries) as Record<string, AgentsScalarInput>;
  for (const field of description.inputSchema) {
    const input = normalized[field.name];
    if (field.required && (input === undefined || (typeof input === 'string' && input.trim().length === 0))) {
      throw new AgentsMcpError('invalid_input', 'Agents invoke is missing a required input');
    }
  }
  return normalized;
}

/** Validates model-provided scalar values and uploaded file URLs against the current exact schema. */
export function validateAgentsInvokeInputs(description: AgentsCatalogDescription, value: unknown): AgentsInvokeInputs {
  return validateInputObject(description, value);
}

/** Validates one upload target and its filename metadata against an exact type=file field. */
export function validateAgentsFileField(
  description: AgentsCatalogDescription,
  fieldName: string,
  fileName: string
): AgentsSchemaField {
  const field = description.inputSchema.find(({ name }) => name === fieldName);
  if (!field || AGENTS_INVOKE_CONTROL_FIELDS.has(fieldName) || field.type.toLowerCase() !== 'file') {
    throw new AgentsMcpError('invalid_input', 'Agents upload target must be an exact file field');
  }
  const allowed = field.allowed_file_types;
  if (!allowed?.length) return field;
  const extension = fileName.includes('.') ? fileName.split('.').at(-1)?.toLowerCase() : undefined;
  const matches = allowed.some((candidate) => {
    const normalized = candidate.trim().toLowerCase();
    if (!normalized) return false;
    if (extension && (normalized === extension || normalized === `.${extension}`)) return true;
    return false;
  });
  if (!matches) throw new AgentsMcpError('invalid_input', 'The attachment type is not allowed for this file field');
  return field;
}
